### ISSUE TITLE
Make the repo code-pattern compliant

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-stock-advisor#7]
Looking good so far team! We need to do a few other things to make this a "code pattern":

1. [x] Create a thorough README.md
2. [x] Create a wiki to draft IBMCode content
3. [x] Add an architectural diagram
4. [x] Add Deploy to IBM Cloud support
5. [x] Create a video
6. [x] Create a blog
7. [x] Add unit tests
8. [x] Add linting tests

* See https://github.com/IBM/watson-discovery-ui as an example for 1-4 and 7
* See https://www.youtube.com/watch?v=SUj826ybCdU as an example of 5
* See https://developer.ibm.com/code/2017/12/01/creating-offline-first-shopping-list-app-polymer-pouchdb/ as an example of 6

**Comment by creitz** [comment]
Also:

1) Architecture diagram
2) Unit Tests

**Comment by rhagarty** [comment]
and lint test

**Comment by stevemar** [comment]
Updating the original comment to make it a checklist...

**Comment by stevemar** [comment]
Just checking in if y'all need help or pointers with any of the items above. Feel free to reach out and grab some time with us if needed.

**Comment by stevemar** [comment]
I spoke with @scottdangelo today, below is my understanding: 

* @creitz and @GJena are doing a blog about this, please get it done quickly
* @scottdangelo cleaned up the README
* @scottdangelo will create a short video 
* @scottdangelo will be drafting up the web page content in the wiki

**Comment by stevemar** [comment]
@creitz any update on that blog? i was hoping to shoot this off to our publishing team this week. You can create it in the wiki directly, just look for the blog section: https://github.com/IBM/watson-stock-advisor/wiki

**Comment by GJena** [comment]
Updated the wiki with the blog

**Comment by stevemar** [comment]
@GJena gracias!

**Comment by stevemar** [comment]
closing this up.
