### ISSUE TITLE
Feature Change Convo Recap

### ISSUE THREAD

**Issue by Reggie-Raye** [IBM/watson-stock-advisor#71]
1. [ ] 3-4 stats (e.g. P/E, div yield, mkt cap) added to chart at top left of page
2. [x] Remove ticker column from chart (or add ticker as a parenthetical next to company name)
3. [x] Consider replacing red delete buttons with one small edit icon inside the Company cell 
4. [x] Change neutral sentiment pie chart color from yellow to light grey
5. [x] Re news articles: either segment according to meaningful categories/concepts and arrange articles according to these buckets, or, otherwise, add 1-5 keyword tags below article icon describing article content
       —> this step is crucial to highlight Discovery enrichments
6. [ ] Optional: add a second graph similar to the co-mentions graph in the Discovery News demo
7. [x] Display high/low and open/close in app header

@ddevara @creitz

**Comment by stevemar** [comment]
@rhagarty FYI on more disco related work.

**Comment by creitz** [comment]
Made the items checkable

**Comment by creitz** [comment]
Not finding a way to get the stats for the first checkbox. If anyone is aware, please let me know.

**Comment by creitz** [comment]
#73

**Comment by stevemar** [comment]
@creitz I looked at the alpha vantage API, looks like there is support for high and low,  couldn't find anything about P/E or yield. @Reggie-Raye how hard of a requirement is that first check box?

**Comment by creitz** [comment]
Is daily high and low what we want? Or over what period? The node package only seems to support daily data, even though the rest API provides weekly and monthly.

**Comment by Reggie-Raye** [comment]
@creitz Don't view the first check box as 100% hard. Would be nice to have real, pertinent data of some kind - w.r.t. daily values preferably. But something here is better than nothing - imo the app loses cred without a true stock dashboard style view

**Comment by GJena** [comment]
@creitz Did you check out the other Alpha Vantage warppers? Some of them are : https://www.npmjs.com/package/alphavantage and https://github.com/stephanepericat/alphavantage-api-node

**Comment by rhagarty** [comment]
Don't know all the history here, so maybe you've already looked at this, but this looks interesting - https://iextrading.com/developer/docs/#key-stats

**Comment by stevemar** [comment]
@creitz @Reggie-Raye @GJena @rhagarty THANKS to everyone involved!! this is published! https://developer.ibm.com/code/patterns/create-a-web-app-to-get-stock-information-prices-and-sentiment/
