### ISSUE TITLE
Code pattern text edits

### ISSUE THREAD

**Issue by Reggie-Raye** [IBM/watson-stock-advisor#72]
All mentions of "Watson News Explorer" on the developerWorks code pattern page should be replaced with "Watson Discovery News"

**Comment by stevemar** [comment]
I updated it, have another look: http://developer.ibm.com/code/?p=34606&post_type=pnext_journey&preview=1&_ppp=9f217fdd39

**Comment by Reggie-Raye** [comment]
Thanks!
