### ISSUE TITLE
Alpha Vantage Acknowledgement

### ISSUE THREAD

**Issue by team-alphavantage** [IBM/watson-stock-advisor#77]
Hello Team IBM, 

We are the support team of Alpha Vantage. Huge fan of the Watson Stock Advisor - we are honored to be part of the journey! 

The title of the [project home page](https://developer.ibm.com/code/patterns/create-a-web-app-to-get-stock-information-prices-and-sentiment/) reads "Use Watson Discovery, Cloudant NoSQL DB, and Node.js to create a web app to monitor sentiment, price, and news for individually listed stocks."

Would it be possible to include Alpha Vantage in the title as well? If you see fit, please feel free to drop us a note at support@alphavantage.co anytime. 

Sincerely, 

Team Alpha Vantage

**Comment by stevemar** [comment]
@team-alphavantage that sounds like a completely reasonable ask. I updated the page to reflect that: https://developer.ibm.com/code/patterns/create-a-web-app-to-get-stock-information-prices-and-sentiment/

**Comment by team-alphavantage** [comment]
Thank you Steve! Much appreicated!
